### ISSUE TITLE
Video-watching capability

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/American-Lang220#1]
First thing this site needs to do is be able to show a video (streaming or otherwise). We can achieve this in one of three ways: HTML5, Adobe Flash, or MSFT silverlight. Pick your favorite technology and go with it. Use whatever decoding you want for now to show the video, however, be forewarned that we will probably shift to H.264 style encoding later down the line.

Create a model that keeps track of unique video-names, their owner, and whatever other information that might be relevant. Then create a controller that allows the user to view a given video.

**Comment by SpinnakerSix** [comment]
deprecated.
