### ISSUE TITLE
Ads transfer protocol

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/American-Lang220#10]
Once a business has decided to sponsor an ad and has given us the banner they want us to display wherever, we need to have a way of communicating with the users to know when to transfer these ad images.

The controller on the server side must keep the ad in a prepared queue. When users using our platform sends up a properly encrypted "request new ad" signal,  we ship the ad to the user and update the statistics. See the scaffold files for more documentation.

**Comment by SpinnakerSix** [comment]
moved to American-Lit-315, adserver
