### ISSUE TITLE
Secure the transfer protocols

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/American-Lang220#11]
Because ads are essentially translated into money, we must enforce some security to prevent malicious users from majorly abusing the system. Here are a few things we must implement:

Cap on maximum ads viewed per second: 1 ads per second per user, anything higher is probably a bot.
RSA on user-platform server communications: we need to make sure we're accurately tracking where our ads are being sent and who is actually interacting with them.

**Comment by SpinnakerSix** [comment]
moved to American-Lit-315, adserver
