### ISSUE TITLE
Image file uploading and management

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/American-Lang220#12]
We need corporate users to be able to upload jpg, gif, and png files which represent banner ads. We must be able to enforce size and dimensions restrictions server-side and provide some sort of interface for the business users to crop and edit their ads after they've been uploaded.

**Comment by trevor-umeda** [comment]
We can use paperclip and imagemagick for this.
I've set it up on another thing so I can attempt this.

Enforcing size dimensions and restrictions can be done there.

Cropping is done with jquery which i've also handled.

**Comment by trevor-umeda** [comment]
Image uploading and cropping done.

Will need to configure with s3 to actually put online though.

**Comment by SpinnakerSix** [comment]
moved to American-Lit-315, adserver
