### ISSUE TITLE
This thing needs to be stripped down for sign up page

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/American-Lang220#17]
There is absolutely no reason why the git slug needs to be 37.44Mb for a single sign-up page with various simple demos as necessary. We need to start a rails app anew for something like this

**Comment by foxnewsnetwork** [comment]
Your bundle is complete! It was installed into ./.bundle/gems/
 !     Heroku push rejected, Procfile is not supported on the Bamboo stack

To git@heroku.com:empty-dawn-1538.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:empty-dawn-1538.git'

Heroku rejects my push because this slug is too massive.

**Comment by SpinnakerSix** [comment]
LOL

I was just thinking about that. Will restart a new app that does this. 

the 37mb are pictures. yes pictures. massive and massive amounts of pictures.
