### ISSUE TITLE
Streaming to the site

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/American-Lang220#4]
The site ought to handle streaming in the traditional way of handling streaming: requesting webcam access. Silverlight, Flash Media server both have ways of handling webcam-capabilities, however, the encoding for them might be different (choose which ever one you'd like). 

Streaming-in data should be saved onto somewhere on the server so create a service that does this and before to let the model know the name of this so the video can be called to replay or be deleted as necessary.

**Comment by SpinnakerSix** [comment]
deprecated.
