### ISSUE TITLE
Corporate accounts

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/American-Lang220#8]
In order to do anything, we first need to have some corporate sponsors. It is only natural, then, that we have a model and controller for corporate accounts. The reason why we don't just add another column in the user section is because we will eventually expand user capabilities and corporation capabilities in different directions, thus requiring two different models and controllers. I realize congress seems to think that corporation are people, but we will not let the decisions of our legislature affect our code

**Comment by trevor-umeda** [comment]
Put this in. Basic stuff. Also included views.

Undoubtedly we'll want more features to distinguish this from users.

This means overwriting the controller and stuff. So when we get there I'll do that stuff and we'll need a new issue.
Till then this is closed.
